name: Code Coverage

on: [push]

jobs:
  codecov:
    container: 
      image: swift:5.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 40
